# coding: utf-8

"""
    Lakoy Public API

    Lakoy Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lakoy.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_read_root_get(self) -> None:
        """Test case for read_root_get

        Read Root  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
