# coding: utf-8

# flake8: noqa
"""
    Lakoy Public API

    Lakoy Public API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
